==2595== Memcheck, a memory error detector
==2595== Copyright (C) 2002-2013, and GNU GPL'd, by Julian Seward et al.
==2595== Using Valgrind-3.10.1 and LibVEX; rerun with -h for copyright info
==2595== Command: ./uriProc
==2595== 
==2595== Invalid write of size 1
==2595==    at 0x405663: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:341)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==  Address 0x5d0243b is 20 bytes after a block of size 7 alloc'd
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x40562C: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:339)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== Invalid write of size 1
==2595==    at 0x4057D0: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:373)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==  Address 0x5d066a2 is 0 bytes after a block of size 2 alloc'd
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x40575E: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:366)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== Invalid read of size 1
==2595==    at 0x55C9943: vfprintf (vfprintf.c:1661)
==2595==    by 0x55D23D8: printf (printf.c:33)
==2595==    by 0x4063C9: up_show(uri_proc_struct*) (uri_proc.c:775)
==2595==    by 0x40670B: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:77)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==  Address 0x5d066a2 is 0 bytes after a block of size 2 alloc'd
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x40575E: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:366)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== Conditional jump or move depends on uninitialised value(s)
==2595==    at 0x55C9943: vfprintf (vfprintf.c:1661)
==2595==    by 0x55D23D8: printf (printf.c:33)
==2595==    by 0x406363: up_show(uri_proc_struct*) (uri_proc.c:771)
==2595==    by 0x406911: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:93)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==  Uninitialised value was created by a heap allocation
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x405F20: up_create_from_host(char*, int, void*) (uri_proc.c:610)
==2595==    by 0x406827: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:90)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x41476A: testing::UnitTest::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== Invalid write of size 1
==2595==    at 0x405663: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:341)
==2595==    by 0x405F91: up_create_from_host(char*, int, void*) (uri_proc.c:618)
==2595==    by 0x406827: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:90)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x41476A: testing::UnitTest::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==  Address 0x5dd21a4 is 13 bytes after a block of size 7 alloc'd
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x40562C: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:339)
==2595==    by 0x405F91: up_create_from_host(char*, int, void*) (uri_proc.c:618)
==2595==    by 0x406827: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:90)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== 
==2595== HEAP SUMMARY:
==2595==     in use at exit: 310,428 bytes in 19,250 blocks
==2595==   total heap usage: 51,309 allocs, 32,059 frees, 1,280,737 bytes allocated
==2595== 
==2595== 4 bytes in 1 blocks are definitely lost in loss record 1 of 8
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x405449: _up_get_top_level_index(char*, int, int) (uri_proc.c:260)
==2595==    by 0x4054EE: _up_get_top_level_index(char*, int, int) (uri_proc.c:273)
==2595==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== 116 bytes in 30 blocks are definitely lost in loss record 2 of 8
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x405449: _up_get_top_level_index(char*, int, int) (uri_proc.c:260)
==2595==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== 140 bytes in 7 blocks are still reachable in loss record 3 of 8
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x405056: _up_load_domain(char**, char*) (uri_proc.c:122)
==2595==    by 0x40530A: _up_is_top_domain(char*, int, int) (uri_proc.c:205)
==2595==    by 0x4054C5: _up_get_top_level_index(char*, int, int) (uri_proc.c:268)
==2595==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== 1,890 bytes in 60 blocks are definitely lost in loss record 4 of 8
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x4064D2: create_string_array_from_file(char**, char*, int*) (UnitTest_uri_proc.c:32)
==2595==    by 0x406D1D: uri_proc::SetUp() (UnitTest_uri_proc.c:55)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E3C5: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x41476A: testing::UnitTest::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== 5,100 bytes in 255 blocks are still reachable in loss record 5 of 8
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x405056: _up_load_domain(char**, char*) (uri_proc.c:122)
==2595==    by 0x40529C: _up_is_top_domain(char*, int, int) (uri_proc.c:194)
==2595==    by 0x4054C5: _up_get_top_level_index(char*, int, int) (uri_proc.c:268)
==2595==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2595==    by 0x405D4E: _up_parse(uri_proc_struct*, char*, int) (uri_proc.c:527)
==2595==    by 0x405E40: up_create(char*, int, void*) (uri_proc.c:582)
==2595==    by 0x406621: uri_proc_up_create_Test::TestBody() (UnitTest_uri_proc.c:74)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== 28,800 bytes in 6,298 blocks are definitely lost in loss record 6 of 8
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x405449: _up_get_top_level_index(char*, int, int) (uri_proc.c:260)
==2595==    by 0x40572B: _up_parse_host(uri_proc_struct*, int) (uri_proc.c:362)
==2595==    by 0x405F91: up_create_from_host(char*, int, void*) (uri_proc.c:618)
==2595==    by 0x406827: uri_proc_up_create_from_host_Test::TestBody() (UnitTest_uri_proc.c:90)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E418: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== 72,704 bytes in 1 blocks are still reachable in loss record 7 of 8
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x50BB62F: ??? (in /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22)
==2595==    by 0x4010109: call_init.part.0 (dl-init.c:78)
==2595==    by 0x40101F2: call_init (dl-init.c:36)
==2595==    by 0x40101F2: _dl_init (dl-init.c:126)
==2595==    by 0x4001309: ??? (in /lib/x86_64-linux-gnu/ld-2.19.so)
==2595== 
==2595== 201,674 bytes in 12,598 blocks are definitely lost in loss record 8 of 8
==2595==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==2595==    by 0x4064D2: create_string_array_from_file(char**, char*, int*) (UnitTest_uri_proc.c:32)
==2595==    by 0x406D3F: uri_proc::SetUp() (UnitTest_uri_proc.c:56)
==2595==    by 0x42E819: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x4287E5: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40E3C5: testing::Test::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40ECA4: testing::TestInfo::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x40F335: testing::TestCase::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x415AE0: testing::internal::UnitTestImpl::RunAllTests() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42FC0F: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x42954B: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595==    by 0x41476A: testing::UnitTest::Run() (in /home/montimage/workspace/montimage/uri_proc/unit_tests/uriProc)
==2595== 
==2595== LEAK SUMMARY:
==2595==    definitely lost: 232,484 bytes in 18,987 blocks
==2595==    indirectly lost: 0 bytes in 0 blocks
==2595==      possibly lost: 0 bytes in 0 blocks
==2595==    still reachable: 77,944 bytes in 263 blocks
==2595==         suppressed: 0 bytes in 0 blocks
==2595== 
==2595== For counts of detected and suppressed errors, rerun with: -v
==2595== ERROR SUMMARY: 6324 errors from 10 contexts (suppressed: 0 from 0)
